# Generated by Django 6.0.5 on 2026-06-04 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favourited',
            field=models.ManyToManyField(blank=True, related_name='favourited_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
